#!/usr/bin/env bash
#
# Write .env.server-test for the LAN-only test instance, with fresh secrets.
#
# Refuses to overwrite: the file holds the only copy of the Postgres password
# protecting ${DATA_DIR}, and regenerating it on top of a live instance would
# leave a database nothing can open. Delete it yourself if you really mean to.
#
# Every secret is generated here and never copied from anywhere — not from
# FreeFrame's .env.prod, not from a FilmBill v1, not from the dev .env. A
# shared secret turns two instances into one blast radius.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/.env.server-test"
EXAMPLE="${REPO_ROOT}/.env.server-test.example"

if [[ -e "${OUT}" ]]; then
  echo "refusing to overwrite ${OUT}" >&2
  echo "" >&2
  echo "It already exists. If the stack is running, this file holds the only" >&2
  echo "copy of the database password for the data in DATA_DIR — replacing it" >&2
  echo "would leave that data unreadable. To start over deliberately:" >&2
  echo "" >&2
  echo "  mv ${OUT} ${OUT}.old" >&2
  echo "  $0" >&2
  exit 1
fi

if [[ ! -f "${EXAMPLE}" ]]; then
  echo "missing ${EXAMPLE} — run this from a full checkout" >&2
  exit 1
fi

# `openssl rand -base64` can emit `+` and `/`. Both are legal in a compose env
# file, but a `$` from another generator would be interpolated by compose and
# a `/` inside a URL-shaped value is a nuisance to eyeball, so the alphabet is
# narrowed to something unambiguous.
rand() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-40}"; }

ask() {
  local prompt="$1" default="$2" answer
  read -r -p "${prompt} [${default}]: " answer || true
  printf '%s' "${answer:-${default}}"
}

echo "FilmBill — LAN test instance environment"
echo "Press Enter to accept each default (they are this server's values)."
echo

LAN_IP="$(ask 'Server LAN IP (static, must be on this host)' '192.168.1.100')"
WEB_PORT="$(ask 'Web port' '3100')"
API_PORT="$(ask 'API port' '8100')"
MINIO_PORT="$(ask 'MinIO S3 port' '9100')"
MAILPIT_UI_PORT="$(ask 'Mailpit UI port' '8125')"
DATA_DIR="$(ask 'DATA_DIR (bind-mount root; survives redeploys)' \
  '/mnt/HDDs/Applications/Dockers/stacks/filmbill-v2-data')"

umask 077
cat > "${OUT}" <<ENV
# FilmBill — LAN-only test instance. GENERATED by scripts/gen-server-test-env.sh
# on $(date -u '+%Y-%m-%dT%H:%M:%SZ'). Not tracked by git.
#
# Every secret below is unique to this instance.

LAN_IP=${LAN_IP}
WEB_PORT=${WEB_PORT}
API_PORT=${API_PORT}
MINIO_PORT=${MINIO_PORT}
MAILPIT_UI_PORT=${MAILPIT_UI_PORT}

DATA_DIR=${DATA_DIR}

POSTGRES_USER=filmbill
POSTGRES_PASSWORD=$(rand 40)
POSTGRES_DB=filmbill

SECRET_KEY=$(rand 64)
JWT_SECRET=$(rand 64)

MINIO_ROOT_USER=fbv2$(rand 12)
MINIO_ROOT_PASSWORD=$(rand 40)
S3_BUCKET=filmbill

MAIL_FROM_ADDRESS=noreply@filmbill.test
MAIL_FROM_NAME=FilmBill (server test)

DOCUMENT_CONCURRENCY=2
EMAIL_CONCURRENCY=2
ENV

chmod 600 "${OUT}"

# Every variable the compose file interpolates must be present, because an
# undefined one resolves to an EMPTY STRING rather than an error — which is
# how a port silently binds to all interfaces instead of the LAN address.
missing=()
while read -r var; do
  grep -qE "^${var}=" "${OUT}" || missing+=("${var}")
# `[A-Z_]+` would stop at the first digit and read ${S3_BUCKET} as "S".
done < <(grep -oE '\$\{[A-Z_][A-Z0-9_]*' "${REPO_ROOT}/docker-compose.server-test.yml" \
         | sed 's/^\${//' | sort -u)

if (( ${#missing[@]} )); then
  echo "" >&2
  echo "generated file is missing variables the compose file uses:" >&2
  printf '  %s\n' "${missing[@]}" >&2
  echo "this is a bug in $0 — fix it rather than editing the file by hand" >&2
  exit 1
fi

echo
echo "wrote ${OUT} (mode 600)"
echo "Next: scripts/server-test-preflight.sh"
