"""platform baseline

The whole schema FilmBill starts from: users (incl. two-factor), the audit
log, notifications, and the two singleton settings tables.

FreeFrame's ~50 migrations are deliberately NOT carried over. They describe a
media product's history — assets, LUTs, share links, transcription, storage
limits — and replaying them here would create tables this app has no models
for, then drop most of them again. This repo's history starts at the schema
it actually has.

Written by hand rather than autogenerated, then verified with `alembic check`
against a database built from it — which caught eight columns declared
nullable here that the models make NOT NULL. CLAUDE.md rule 9: every schema
change from here on is a migration, and "reset the database" is never a step.

Revision ID: 0001_platform_baseline
Revises:
Create Date: 2026-09-19
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_platform_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "deactivated",
                "pending_invite",
                "pending_verification",
                name="userstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("superadmin", "superuser", "user", name="userglobalrole"),
            server_default="user",
            nullable=False,
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("invite_token", sa.String(length=64), nullable=True),
        sa.Column("invite_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preferences", sa.JSON(), server_default="{}", nullable=False),
        # Two-factor. The secret is Fernet ciphertext, never plaintext; the
        # backup codes are bcrypt hashes. See models/user.py.
        sa.Column("totp_secret_encrypted", sa.String(length=512), nullable=True),
        sa.Column(
            "two_factor_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("two_factor_method", sa.String(length=16), nullable=True),
        sa.Column("backup_codes_hashed", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_invite_token"), "users", ["invite_token"], unique=False)

    op.create_table(
        "activity_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # SET NULL, not CASCADE: losing the actor must not lose the record
        # that the action happened.
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_activity_logs_user_id"), "activity_logs", ["user_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # CASCADE: a notification with no one left to receive it is
        # meaningless, unlike an audit row.
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.Enum("account", name="notificationtype"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.String(length=2000), nullable=True),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column("read", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)

    op.create_table(
        "site_settings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("org_name", sa.String(), server_default="FilmBill", nullable=False),
        sa.Column("logo_dark_s3_key", sa.String(), nullable=True),
        sa.Column("logo_light_s3_key", sa.String(), nullable=True),
        sa.Column("logo_login_s3_key", sa.String(), nullable=True),
        sa.Column("favicon_s3_key", sa.String(), nullable=True),
        sa.Column("theme_colors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "require_2fa",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "email_settings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("mail_provider", sa.String(length=20), nullable=True),
        sa.Column("mail_from_address", sa.String(length=255), nullable=True),
        sa.Column("mail_from_name", sa.String(length=255), nullable=True),
        sa.Column("aws_mail_access_key_id", sa.String(length=255), nullable=True),
        # Fernet ciphertext, never plaintext. Wider than the plaintext needs:
        # Fernet output is base64 and meaningfully larger than its input.
        sa.Column("aws_mail_secret_access_key_encrypted", sa.String(length=2000), nullable=True),
        sa.Column("aws_mail_region", sa.String(length=64), nullable=True),
        sa.Column("smtp_host", sa.String(length=255), nullable=True),
        sa.Column("smtp_port", sa.Integer(), nullable=True),
        sa.Column("smtp_user", sa.String(length=255), nullable=True),
        sa.Column("smtp_password_encrypted", sa.String(length=2000), nullable=True),
        sa.Column("smtp_use_tls", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    op.drop_table("email_settings")
    op.drop_table("site_settings")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_activity_logs_user_id"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_users_invite_token"), table_name="users")
    op.drop_table("users")
    # Enum types are not dropped by drop_table on PostgreSQL.
    sa.Enum(name="notificationtype").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="userglobalrole").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="userstatus").drop(op.get_bind(), checkfirst=True)
